### ISSUE TITLE
Conversion to TypeScript moved the exported function to `{ default }`

### ISSUE THREAD

**Issue by prantlf** [neurosnap/gen-readlines#25]
Projects using ESM do not see a differents, but projects using XJS will have to change the original code:

```js
const readlines = require('readlines')
```

to this:

```js
const readlines = require('readlines').default
```

How about getting rid of the `{ default }` wrapper and exporting `readlines` directly again?

This is not only annoying, but also dangerous for compatiblity. If you replace TypeScript with a different transpiler, or if you introduce an ESM -> CJS bundler later, the `{ default }` wrapper may be dissolved, like babel or Rollup do it, when the build target is CJS.

The `{ default }` wrapper [can be avoided in CJS output by using TypeScript-specific syntax](https://github.com/microsoft/TypeScript/issues/2719#issuecomment-289317065). Instead of

```ts
export default readlines
```

use this:

```ts
export = readlines
```

Another solution is [transpiling from TypeScript to ESM and using other bundler for the ESM -> CJS conversion](https://github.com/microsoft/TypeScript/issues/2719#issuecomment-111017623).

An example of the situation after upgrading to 1.0.0:

    ❯ node perf
    Reading lines using...
      byline x 174 ops/sec ±2.41% (81 runs sampled)
      line-reader x 178 ops/sec ±1.48% (83 runs sampled)
      linebyline x 116 ops/sec ±0.59% (89 runs sampled)
      readline x 269 ops/sec ±3.75% (79 runs sampled)
    /Users/prantlf/Sources/github/gen-readlines/perf/index.js:48
          for (const line of readlines(fd, stats.size)) {
                             ^

    TypeError: readlines is not a function or its return value is not iterable
        at /Users/prantlf/Sources/github/gen-readlines/perf/index.js:48:26
        at FSReqCallback.oncomplete (node:fs:199:5)
